### ISSUE TITLE
Starter fails to run in development due to an error while sourcing data.

### ISSUE THREAD

**Issue by danielclough** [GatsbyStorefront/gatsby-starter-storefront-shopify#2]
- `gatsby-theme-storefront-shopify` version: 2.1.2
- `react` version: 16.13.1
- `Gatsby CLI` version: 2.11.13
- `Gatsby` version: 2.20.29
- `browser` used: Mozilla Firefox 73.0.1
- `node` version: v13.5.0

### Relevant code or config:
 default starter

### What you did:
install default starter
`gatsby develop`
`yarn upgrade`
`gatsby build`

### What happened:

`an error occurred while sourcing data`
Full error log here:
https://gist.github.com/danielclough/3e4b49a5976131c527477f8713f2aa47

### Reproduction:
I am starting with `gatsby new storefront-shopify https://github.com/GatsbyStorefront/gatsby-starter-storefront-shopify` and trying to run `gatsby develop`

### Problem description:

Fails to build.

### Suggested solution:

No idea.

### Can you help us fix this issue by submitting a pull request?

If I am able.

**Comment by paveli** [comment]
Hi @danielclough,
Seems like you didn't create .env file.
Please follow installation instructions from here: https://github.com/GatsbyStorefront/gatsby-theme-storefront-shopify

**Comment by danielclough** [comment]
Just in case, before adding a bug report, I did use my shops .env data, and
this one below with the fresh starter - and got same/similar errors.

Getting the same errors with and without adding a .env file I figured not
adding one is more minimal, sorry for the confusion.

SHOP_NAME=graphql
SHOPIFY_ACCESS_TOKEN=dd4d4dc146542ba7763305d71d1b3d38

Here is an error log after adding the above .env data (working with another
project).

https://gist.github.com/danielclough/08986878e6de002f187aa2671834d6de

**Comment by paveli** [comment]
@danielclough Please note that having a store policies is a requirement (https://github.com/GatsbyStorefront/gatsby-theme-storefront-shopify/blob/master/README.md#shopify-content-requirement).

Here is how to add them: 
https://help.shopify.com/en/manual/checkout-settings/refund-privacy-tos

**Comment by danielclough** [comment]
The site that I have been using with this starter has refunds,
privacy policy, and terms of service.
I can make a gist with the errors I started getting from that site.

The site his working at https://immodestea.com from before the errors
started.
All of those links are working fine in the last version that built.

**Comment by paveli** [comment]
@danielclough please provide the build log for the site you want to troubleshoot. Also please run `gatsby clean` before building.

**Comment by danielclough** [comment]
I have policy data in shopify for refunds, privacy policy, shipping policy,
and terms of service - which is everything in the legal page. Are there are
any other non-obvious requirements that could be causing the issue?


```
Cannot read property 'policies' of undefined

  298 |     }
  299 |   `);
> 300 |   queryPolicies.data.policies.nodes.forEach(({ type, fields }) => {
      |                      ^
  301 |     const { shopifyThemePath } = fields;
  302 |     createPage({
  303 |       path: shopifyThemePath,

File:
node_modules/@gatsbystorefront/gatsby-theme-storefront-shopify/gatsby-node.js:300:22
```

Also, I noticed that alt text for pictures are also required, but not
mentioned in the README.
Is there a way of indicating for what pictures are causing that kind of
issue in the error log? I had to go though every picture to check by hand.
:(

**Comment by danielclough** [comment]
Not sure if this is what you are looking for?
When I search "build log" in the docs it comes up with
https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/#reporting-what-has-been-built

I don't think that's what you are looking for?

daniel@daniel-N5050:~/Git/gatsby/Immodestea-GhostStorefront$ gatsby clean
info Deleting .cache, public
info Successfully deleted directories
daniel@daniel-N5050:~/Git/gatsby/Immodestea-GhostStorefront$ gatsby build
--verbose
verbose set gatsby_log_level: "verbose"
verbose set gatsby_executing_command: "build"
verbose loading local command from:
/home/daniel/Git/gatsby/Immodestea-GhostStorefront/node_modules/gatsby/dist/commands/build.js
verbose running command: build
success open and validate gatsby-configs - 0.676s
success load plugins - 2.273s
success onPreInit - 0.025s
success delete html and css files from previous builds - 0.026s
success initialize cache - 0.020s
success copy gatsby files - 0.074s
warn gatsby-plugin-feed was initialized in gatsby-config.js without a title
in a feed.
This means that the plugin will use the default feed title, which may not
match your use case.
This behavior will be removed in the next major release of
gatsby-plugin-feed.
For more info, check out: https://gatsby.dev/adding-rss-feed
success onPreBootstrap - 0.021s
success createSchemaCustomization - 0.015s

gatsby-source-shopify/immodestea starting to fetch data from Shopify

 ERROR


error an error occurred while sourcing data


 ERROR

query:
  """

      query GetCollections($first: Int!, $after: String) {
        collections(first: $first, after: $after) {
          pageInfo {
            hasNextPage
          }
          edges {
            cursor
            node {
              description
              descriptionHtml
              handle
              id
              image {
                altText
                id
                src
              }
              products(first: 250) {
                edges {
                  node {
                    id
                  }
                }
              }
              title
              updatedAt
            }
          }
        }
      }

  """
variables:
  first: 250
  after: null

warn The gatsby-source-shopify plugin has generated no Gatsby nodes. Do you
need it?
warn The @gatsby-contrib/gatsby-plugin-elasticlunr-search plugin has
generated no Gatsby nodes. Do you need it?
success source and transform nodes - 1.243s
success building schema - 1.379s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allShopifyCollection" on type "Query".

If you don't expect "allShopifyCollection" to exist on the type "Query" it
is most likely a typo.
However, if you expect "allShopifyCollection" to exist there are a couple
of solutions to common problems:

- If you added a new data source and/or changed something inside
gatsby-node.js/gatsby-config.js, please try a restart of your development
server
- The field might be accessible in another subfield, please try your query
in GraphiQL and use the GraphiQL explorer to see which fields you can query
and what shape they have
- You want to optionally use your field "allShopifyCollection" and right
now it is not used anywhere. Therefore Gatsby can't infer the type and add
it to the GraphQL schema. A quick fix is to add a least one entry with that
field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use
optional fields. This way you don't have to add the mentioned "dummy
content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File:
node_modules/@gatsbystorefront/gatsby-theme-storefront-shopify/gatsby-node.js:484:9

not finished createPages - 0.147s

 ERROR #11321  PLUGIN

"@gatsbystorefront/gatsby-theme-storefront-shopify" threw an error while
running the createPages lifecycle:

Cannot read property 'activities' of undefined

  212 |   finalCartPagePath
  213 | ) => {
> 214 |   const queryCollections = await graphql(`
      |                            ^
  215 |     {
  216 |       collections: allShopifyCollection {
  217 |         nodes {

File:
node_modules/@gatsbystorefront/gatsby-theme-storefront-shopify/gatsby-node.js:214:28

**Comment by paveli** [comment]
@danielclough Please provide full built log. 
Maybe you can email me your `.env` file for this store so I could try to build it myself.

**Comment by danielclough** [comment]
I am not sure where the "build log" is located.

.env
GATSBY_SHOP_NAME=immodestea
GATSBY_SHOPIFY_ACCESS_TOKEN=74920b3af99483f11dd722d0967620d1

How sensitive is this data?
Should I reset the access token after the troubleshooting is over?

**Comment by paveli** [comment]
@danielclough for some reason Shopify returns 403 (forbidden) response for graphql api requests to your shop. 
Maybe you have set up password protection or some other settings. Maybe your plan is not active. 
As it was working before, try to remember what settings did you change.

You can use this request to test graphql endpoint for testing:

```
curl -i -X POST \
"https://immodestea.myshopify.com/api/2019-07/graphql" \
-H "Accept: application/json" \
-H "Content-Type: application/graphql" \
-H "X-Shopify-Storefront-Access-Token: 74920b3af99483f11dd722d0967620d1" \
-d '
{
  shop {
    name
    primaryDomain {
      url
      host
    }
  }
}
'
```

Once you will fix this issue the storefront will start to build.

**Comment by paveli** [comment]
@danielclough 
> How sensitive is this data?
> Should I reset the access token after the troubleshooting is over?

Somewhat sensitive. Better change it after you finish troubleshooting.

**Comment by danielclough** [comment]
Thank you very much!
Everything makes sense now.
I reset the shopify API and everything is working again.

Also, I appreciate watching the starter design come together.
The first thing I did was change the shopping bag to my logo, and reading
your update made me think about contributing, and what best practices I
might need to understand for theme development.

**Comment by paveli** [comment]
@danielclough nice! Glad everything is working. I am closing the issue then.
