### ISSUE TITLE
Error testing deployment in Netlify

### ISSUE THREAD

**Issue by coyr** [GatsbyStorefront/gatsby-starter-storefront-shopify#3]
### What you did:

I try to deploy the starter from https://www.gatsbyjs.org/starters/GatsbyStorefront/gatsby-starter-storefront-shopify/

### What happened:

Netlify response was "Site deploy failed"

### Reproduction:

Try to deploy the starter from https://www.gatsbyjs.org/starters/GatsbyStorefront/gatsby-starter-storefront-shopify/
You will get the Netlify response

### Problem description:

It is not clear I tryed locally but I am solving other error with yarn and I don't know if it is related

### Suggested solution:

Check what is braking the code, currently I don't know how to solve it

### Can you help us fix this issue by submitting a pull request?

I will try after I fix my yarn issues locally.

**Comment by paveli** [comment]
@coyr everything should work fine. I will close this issue as it is rather old. Please reopen if it is still relevant and please attach a build log.
